name: NPM Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Publish Core Package
      run: |
        npm ci
        npm test
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish React Package
      run: |
        npm i
        npm publish
      working-directory: ./bindings/react
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}